// Generated by CoffeeScript 1.3.3

/*

User: mmarinucci
Copyright © mename 2013 All rights reserved
MultiBeatServer
*/


(function() {
  var MultiBeatServer, root;

  MultiBeatServer = (function() {

    function MultiBeatServer() {}

    return MultiBeatServer;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.MultiBeatServer = MultiBeatServer;

}).call(this);
