// Generated by CoffeeScript 1.3.3

/*User: mmarinucci
Copyright © mename 2013 All rights reserved
EventManager
*/


(function() {
  var EventManager, root;

  EventManager = (function() {

    function EventManager() {}

    EventManager.publish = function(name, data, node) {
      var event;
      if (node == null) {
        node = document;
      }
      event = document.createEvent('Event');
      event.initEvent(name, true, true);
      event.customData = data;
      return node.dispatchEvent(event);
    };

    EventManager.subscribe = function(name, callback, node) {
      if (node == null) {
        node = document;
      }
      return node.addEventListener(name, (function(event) {
        return callback(event.customData, event);
      }), true);
    };

    EventManager.unsubscribe = function(name, callback, node) {
      if (node == null) {
        node = document;
      }
      return node.removeEventListener(name, (function(event) {
        return callback(event.customData, event);
      }), true);
    };

    return EventManager;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.EventManager = EventManager;

}).call(this);
