// Generated by CoffeeScript 1.3.3

/*
User: matteo
Copyright © mename 2013 All rights reserved
main - Entry point for multibeatt
*/


(function() {
  var client, connection, images, imagesLoaded, imgSources, init, initApp, onImageLoaded, preloadImage, requestAnimFrame, requiredFiles, socket, socketUrl, soundMainfest, soundsLoaded;

  requiredFiles = ['Connection', 'EventManager', 'MultiBeatClient'];

  imgSources = [];

  images = [];

  imagesLoaded = 0;

  soundMainfest = [
    {
      id: "00",
      src: "src/00.wav"
    }, {
      id: "01",
      src: "src/01.wav"
    }, {
      id: "02",
      src: "src/02.wav"
    }, {
      id: "03",
      src: "src/03.wav"
    }
  ];

  soundsLoaded = 0;

  socketUrl = 'http://localhost:1337/';

  socket = null;

  connection = null;

  client = null;

  preloadImage = function(imgSrc) {
    var i, _i, _ref, _results;
    if (imgSrc.length > 0) {
      _results = [];
      for (i = _i = 0, _ref = imgSrc.length; _i < _ref; i = _i += 1) {
        images[i] = new Image();
        images[i].onload = onImageLoaded;
        _results.push(images[i].src = imgSources[i]);
      }
      return _results;
    } else {
      return initApp();
    }
  };

  onImageLoaded = function(event) {
    imagesLoaded++;
    if (imagesLoaded >= imgSources.length) {
      return initApp();
    }
  };

  init = function(element) {
    $(document.body).addClass('ready');
    preloadImage(imgSources);
  };

  initApp = function() {
    var assetPath,
      _this = this;
    connection = new Connection(socketUrl);
    $("#create").click(function() {
      console.log('click create');
      return connection.create(function() {
        return $("#menuButtons").fadeOut();
      });
    });
    $("#join").click(function() {
      console.log('join');
      return connection.join(0, function() {
        console.log('connection join complete');
        return $("#menuButtons").fadeOut();
      });
    });
    client = new MultiBeatClient();
    /*socket = io.connect socketUrl
    socket.on 'connect', (message) ->
        console.log 'connected'
    
    socket.on 'greetings', (message) ->
        console.log "MESSAGE: #{message}"
    */

    assetPath = 'src/00.wav';
    /*createjs.Sound.addEventListener 'fileload', (event) ->
        console.log 'sound play'
        createjs.Sound.play event.src
    createjs.Sound.registerSound assetPath
    */

    createjs.Sound.addEventListener('fileload', function(event) {
      if (++soundsLoaded >= soundMainfest.length) {
        return console.log('all sounds loaded');
      }
    });
    createjs.Sound.addEventListener('loadComplete', function(event) {
      console.log('manifest loaded');
      return console.log(event);
    });
    createjs.Sound.registerManifest(soundMainfest, './');
  };

  requestAnimFrame = (function() {
    return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback) {
      return window.setTimeout(callback, 1000 / 60);
    };
  })();

  require(requiredFiles, init);

}).call(this);
